language: node_js
node_js:
 - "node"

cache: npm

script: npm run --prefix ./reg-mac-frontend build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: reg-mac-frontend/dist
 on:
   branch: master
