# Generated by Django 2.2.6 on 2019-12-04 11:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='hint',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='program',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
